# Generated by Django 5.2.6 on 2025-10-08 03:58

import django.db.models.deletion
import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_is_active_product_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=shop.models.get_default_category, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(default=shop.models.get_default_supplier, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.supplier'),
        ),
    ]
